# Override the default limit of 1024 bytes in ctest_test() output.
# This does not affect the plaintext logs generated by each unit test,
# only the XML output generated for Jenkins to record and display results.
# Increase this number (in bytes) if a unit test is expected to generate more output.
set(CTEST_CUSTOM_MAXIMUM_PASSED_TEST_OUTPUT_SIZE 262144)
