# CMake generated Testfile for 
# Source directory: /Users/poojitaraj/Constraint/reb/721-P3-Constraints/test/catalog
# Build directory: /Users/poojitaraj/Constraint/reb/721-P3-Constraints/src/test/catalog
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(CMakeCXXCompilerId "/Users/poojitaraj/Constraint/reb/721-P3-Constraints/build-support/run-test.sh" "/Users/poojitaraj/Constraint/reb/721-P3-Constraints/src" "test" "/Users/poojitaraj/Constraint/reb/721-P3-Constraints/test/catalog/CMakeCXXCompilerId")
set_tests_properties(CMakeCXXCompilerId PROPERTIES  LABELS "unittest" _BACKTRACE_TRIPLES "/Users/poojitaraj/Constraint/reb/721-P3-Constraints/cmake_modules/BuildUtils.cmake;323;add_test;/Users/poojitaraj/Constraint/reb/721-P3-Constraints/cmake_modules/BuildUtils.cmake;333;ADD_TERRIER_TEST;/Users/poojitaraj/Constraint/reb/721-P3-Constraints/test/catalog/CMakeLists.txt;1;ADD_TERRIER_TESTS;/Users/poojitaraj/Constraint/reb/721-P3-Constraints/test/catalog/CMakeLists.txt;0;")
add_test(catalog_test "/Users/poojitaraj/Constraint/reb/721-P3-Constraints/build-support/run-test.sh" "/Users/poojitaraj/Constraint/reb/721-P3-Constraints/src" "test" "/Users/poojitaraj/Constraint/reb/721-P3-Constraints/src/release//catalog_test")
set_tests_properties(catalog_test PROPERTIES  LABELS "unittest" _BACKTRACE_TRIPLES "/Users/poojitaraj/Constraint/reb/721-P3-Constraints/cmake_modules/BuildUtils.cmake;323;add_test;/Users/poojitaraj/Constraint/reb/721-P3-Constraints/cmake_modules/BuildUtils.cmake;333;ADD_TERRIER_TEST;/Users/poojitaraj/Constraint/reb/721-P3-Constraints/test/catalog/CMakeLists.txt;1;ADD_TERRIER_TESTS;/Users/poojitaraj/Constraint/reb/721-P3-Constraints/test/catalog/CMakeLists.txt;0;")
add_test(constraint_statement_test "/Users/poojitaraj/Constraint/reb/721-P3-Constraints/build-support/run-test.sh" "/Users/poojitaraj/Constraint/reb/721-P3-Constraints/src" "test" "/Users/poojitaraj/Constraint/reb/721-P3-Constraints/src/release//constraint_statement_test")
set_tests_properties(constraint_statement_test PROPERTIES  LABELS "unittest" _BACKTRACE_TRIPLES "/Users/poojitaraj/Constraint/reb/721-P3-Constraints/cmake_modules/BuildUtils.cmake;323;add_test;/Users/poojitaraj/Constraint/reb/721-P3-Constraints/cmake_modules/BuildUtils.cmake;333;ADD_TERRIER_TEST;/Users/poojitaraj/Constraint/reb/721-P3-Constraints/test/catalog/CMakeLists.txt;1;ADD_TERRIER_TESTS;/Users/poojitaraj/Constraint/reb/721-P3-Constraints/test/catalog/CMakeLists.txt;0;")
add_test(name_builder_test "/Users/poojitaraj/Constraint/reb/721-P3-Constraints/build-support/run-test.sh" "/Users/poojitaraj/Constraint/reb/721-P3-Constraints/src" "test" "/Users/poojitaraj/Constraint/reb/721-P3-Constraints/src/release//name_builder_test")
set_tests_properties(name_builder_test PROPERTIES  LABELS "unittest" _BACKTRACE_TRIPLES "/Users/poojitaraj/Constraint/reb/721-P3-Constraints/cmake_modules/BuildUtils.cmake;323;add_test;/Users/poojitaraj/Constraint/reb/721-P3-Constraints/cmake_modules/BuildUtils.cmake;333;ADD_TERRIER_TEST;/Users/poojitaraj/Constraint/reb/721-P3-Constraints/test/catalog/CMakeLists.txt;1;ADD_TERRIER_TESTS;/Users/poojitaraj/Constraint/reb/721-P3-Constraints/test/catalog/CMakeLists.txt;0;")
