SELECT NO_O_ID FROM "NEW ORDER" WHERE NO_D_ID = 1 AND NO_W_ID = 2 ORDER BY NO_O_ID LIMIT 1
DELETE FROM "NEW ORDER" WHERE NO_O_ID = 1 AND NO_D_ID = 2 AND NO_W_ID = 3
SELECT O_C_ID FROM "ORDER" WHERE O_ID = 1 AND (O_D_ID = 2 AND O_W_ID = 3)
UPDATE "ORDER" SET O_CARRIER_ID = 1 WHERE O_ID = 1 AND O_D_ID = 2 AND O_W_ID = 3
UPDATE "ORDER LINE" SET OL_DELIVERY_D = 1 WHERE OL_O_ID = 1 AND OL_D_ID = 2 AND OL_W_ID = 3
SELECT SUM(OL_AMOUNT) AS OL_TOTAL FROM "ORDER LINE" WHERE OL_O_ID=1 AND OL_D_ID=2 AND OL_W_ID=3
UPDATE CUSTOMER SET C_BALANCE = C_BALANCE+1, C_DELIVERY_CNT=C_DELIVERY_CNT+1 WHERE C_W_ID=1 AND C_D_ID=2 AND C_ID=3
