SELECT NO_O_ID FROM "NEW ORDER" WHERE NO_D_ID = 1
SELECT NO_O_ID FROM "NEW ORDER" WHERE 1 < NO_D_ID
SELECT NO_O_ID FROM "NEW ORDER" ORDER BY NO_W_ID
SELECT NO_O_ID FROM "NEW ORDER" ORDER BY NO_W_ID DESC
SELECT NO_O_ID FROM "NEW ORDER" ORDER BY NO_D_ID
SELECT NO_O_ID FROM "NEW ORDER" ORDER BY NO_W_ID, NO_D_ID DESC
SELECT NO_O_ID FROM "NEW ORDER" WHERE NO_W_ID = 1 ORDER BY NO_W_ID
SELECT NO_O_ID FROM "NEW ORDER" WHERE NO_W_ID = 1 ORDER BY NO_W_ID LIMIT 15 OFFSET 445
