SELECT D_NEXT_O_ID FROM DISTRICT WHERE D_W_ID=1 AND D_ID=2
SELECT COUNT(DISTINCT S_I_ID) AS STOCK_COUNT FROM "ORDER LINE", STOCK WHERE OL_W_ID = 1 AND OL_D_ID = 2 AND OL_O_ID < 3 AND OL_O_ID >= 4 AND S_W_ID = 5 AND S_I_ID = OL_I_ID AND S_QUANTITY < 6
SELECT S_I_ID FROM "ORDER LINE", STOCK WHERE OL_W_ID=1 AND S_W_ID=1 AND OL_W_ID=S_W_ID
