# CMake generated Testfile for 
# Source directory: /home/amlatyr/Code/terrier/test/execution
# Build directory: /home/amlatyr/Code/terrier/test/execution
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(aggregation_hash_table_test "/home/amlatyr/Code/terrier/build-support/run-test.sh" "/home/amlatyr/Code/terrier" "test" "/home/amlatyr/Code/terrier/build/debug//aggregation_hash_table_test")
set_tests_properties(aggregation_hash_table_test PROPERTIES  LABELS "unittest")
add_test(aggregators_test "/home/amlatyr/Code/terrier/build-support/run-test.sh" "/home/amlatyr/Code/terrier" "test" "/home/amlatyr/Code/terrier/build/debug//aggregators_test")
set_tests_properties(aggregators_test PROPERTIES  LABELS "unittest")
add_test(arithmetic_functions_test "/home/amlatyr/Code/terrier/build-support/run-test.sh" "/home/amlatyr/Code/terrier" "test" "/home/amlatyr/Code/terrier/build/debug//arithmetic_functions_test")
set_tests_properties(arithmetic_functions_test PROPERTIES  LABELS "unittest")
add_test(ast_context_test "/home/amlatyr/Code/terrier/build-support/run-test.sh" "/home/amlatyr/Code/terrier" "test" "/home/amlatyr/Code/terrier/build/debug//ast_context_test")
set_tests_properties(ast_context_test PROPERTIES  LABELS "unittest")
add_test(ast_test "/home/amlatyr/Code/terrier/build-support/run-test.sh" "/home/amlatyr/Code/terrier" "test" "/home/amlatyr/Code/terrier/build/debug//ast_test")
set_tests_properties(ast_test PROPERTIES  LABELS "unittest")
add_test(ast_traversal_visitor_test "/home/amlatyr/Code/terrier/build-support/run-test.sh" "/home/amlatyr/Code/terrier" "test" "/home/amlatyr/Code/terrier/build/debug//ast_traversal_visitor_test")
set_tests_properties(ast_traversal_visitor_test PROPERTIES  LABELS "unittest")
add_test(bandit_test "/home/amlatyr/Code/terrier/build-support/run-test.sh" "/home/amlatyr/Code/terrier" "test" "/home/amlatyr/Code/terrier/build/debug//bandit_test")
set_tests_properties(bandit_test PROPERTIES  LABELS "unittest")
add_test(bit_util_test "/home/amlatyr/Code/terrier/build-support/run-test.sh" "/home/amlatyr/Code/terrier" "test" "/home/amlatyr/Code/terrier/build/debug//bit_util_test")
set_tests_properties(bit_util_test PROPERTIES  LABELS "unittest")
add_test(bitfield_test "/home/amlatyr/Code/terrier/build-support/run-test.sh" "/home/amlatyr/Code/terrier" "test" "/home/amlatyr/Code/terrier/build/debug//bitfield_test")
set_tests_properties(bitfield_test PROPERTIES  LABELS "unittest")
add_test(bloom_filter_test "/home/amlatyr/Code/terrier/build-support/run-test.sh" "/home/amlatyr/Code/terrier" "test" "/home/amlatyr/Code/terrier/build/debug//bloom_filter_test")
set_tests_properties(bloom_filter_test PROPERTIES  LABELS "unittest")
add_test(bytecode_generator_test "/home/amlatyr/Code/terrier/build-support/run-test.sh" "/home/amlatyr/Code/terrier" "test" "/home/amlatyr/Code/terrier/build/debug//bytecode_generator_test")
set_tests_properties(bytecode_generator_test PROPERTIES  LABELS "unittest")
add_test(bytecode_iterator_test "/home/amlatyr/Code/terrier/build-support/run-test.sh" "/home/amlatyr/Code/terrier" "test" "/home/amlatyr/Code/terrier/build/debug//bytecode_iterator_test")
set_tests_properties(bytecode_iterator_test PROPERTIES  LABELS "unittest")
add_test(bytecode_trampoline_test "/home/amlatyr/Code/terrier/build-support/run-test.sh" "/home/amlatyr/Code/terrier" "test" "/home/amlatyr/Code/terrier/build/debug//bytecode_trampoline_test")
set_tests_properties(bytecode_trampoline_test PROPERTIES  LABELS "unittest")
add_test(bytecodes_test "/home/amlatyr/Code/terrier/build-support/run-test.sh" "/home/amlatyr/Code/terrier" "test" "/home/amlatyr/Code/terrier/build/debug//bytecodes_test")
set_tests_properties(bytecodes_test PROPERTIES  LABELS "unittest")
add_test(chunked_vector_test "/home/amlatyr/Code/terrier/build-support/run-test.sh" "/home/amlatyr/Code/terrier" "test" "/home/amlatyr/Code/terrier/build/debug//chunked_vector_test")
set_tests_properties(chunked_vector_test PROPERTIES  LABELS "unittest")
add_test(concise_hash_table_test "/home/amlatyr/Code/terrier/build-support/run-test.sh" "/home/amlatyr/Code/terrier" "test" "/home/amlatyr/Code/terrier/build/debug//concise_hash_table_test")
set_tests_properties(concise_hash_table_test PROPERTIES  LABELS "unittest")
add_test(filter_manager_test "/home/amlatyr/Code/terrier/build-support/run-test.sh" "/home/amlatyr/Code/terrier" "test" "/home/amlatyr/Code/terrier/build/debug//filter_manager_test")
set_tests_properties(filter_manager_test PROPERTIES  LABELS "unittest")
add_test(generic_hash_table_test "/home/amlatyr/Code/terrier/build-support/run-test.sh" "/home/amlatyr/Code/terrier" "test" "/home/amlatyr/Code/terrier/build/debug//generic_hash_table_test")
set_tests_properties(generic_hash_table_test PROPERTIES  LABELS "unittest")
add_test(hash_test "/home/amlatyr/Code/terrier/build-support/run-test.sh" "/home/amlatyr/Code/terrier" "test" "/home/amlatyr/Code/terrier/build/debug//hash_test")
set_tests_properties(hash_test PROPERTIES  LABELS "unittest")
add_test(is_null_predicate_test "/home/amlatyr/Code/terrier/build-support/run-test.sh" "/home/amlatyr/Code/terrier" "test" "/home/amlatyr/Code/terrier/build/debug//is_null_predicate_test")
set_tests_properties(is_null_predicate_test PROPERTIES  LABELS "unittest")
add_test(join_hash_table_test "/home/amlatyr/Code/terrier/build-support/run-test.sh" "/home/amlatyr/Code/terrier" "test" "/home/amlatyr/Code/terrier/build/debug//join_hash_table_test")
set_tests_properties(join_hash_table_test PROPERTIES  LABELS "unittest")
add_test(join_hash_table_vector_probe_test "/home/amlatyr/Code/terrier/build-support/run-test.sh" "/home/amlatyr/Code/terrier" "test" "/home/amlatyr/Code/terrier/build/debug//join_hash_table_vector_probe_test")
set_tests_properties(join_hash_table_vector_probe_test PROPERTIES  LABELS "unittest")
add_test(math_util_test "/home/amlatyr/Code/terrier/build-support/run-test.sh" "/home/amlatyr/Code/terrier" "test" "/home/amlatyr/Code/terrier/build/debug//math_util_test")
set_tests_properties(math_util_test PROPERTIES  LABELS "unittest")
add_test(parsing_test "/home/amlatyr/Code/terrier/build-support/run-test.sh" "/home/amlatyr/Code/terrier" "test" "/home/amlatyr/Code/terrier/build/debug//parsing_test")
set_tests_properties(parsing_test PROPERTIES  LABELS "unittest")
add_test(projected_columns_iterator_test "/home/amlatyr/Code/terrier/build-support/run-test.sh" "/home/amlatyr/Code/terrier" "test" "/home/amlatyr/Code/terrier/build/debug//projected_columns_iterator_test")
set_tests_properties(projected_columns_iterator_test PROPERTIES  LABELS "unittest")
add_test(region_test "/home/amlatyr/Code/terrier/build-support/run-test.sh" "/home/amlatyr/Code/terrier" "test" "/home/amlatyr/Code/terrier/build/debug//region_test")
set_tests_properties(region_test PROPERTIES  LABELS "unittest")
add_test(scanner_test "/home/amlatyr/Code/terrier/build-support/run-test.sh" "/home/amlatyr/Code/terrier" "test" "/home/amlatyr/Code/terrier/build/debug//scanner_test")
set_tests_properties(scanner_test PROPERTIES  LABELS "unittest")
add_test(sema_builtin_test "/home/amlatyr/Code/terrier/build-support/run-test.sh" "/home/amlatyr/Code/terrier" "test" "/home/amlatyr/Code/terrier/build/debug//sema_builtin_test")
set_tests_properties(sema_builtin_test PROPERTIES  LABELS "unittest")
add_test(sema_expr_test "/home/amlatyr/Code/terrier/build-support/run-test.sh" "/home/amlatyr/Code/terrier" "test" "/home/amlatyr/Code/terrier/build/debug//sema_expr_test")
set_tests_properties(sema_expr_test PROPERTIES  LABELS "unittest")
add_test(sorter_test "/home/amlatyr/Code/terrier/build-support/run-test.sh" "/home/amlatyr/Code/terrier" "test" "/home/amlatyr/Code/terrier/build/debug//sorter_test")
set_tests_properties(sorter_test PROPERTIES  LABELS "unittest")
add_test(string_functions_test "/home/amlatyr/Code/terrier/build-support/run-test.sh" "/home/amlatyr/Code/terrier" "test" "/home/amlatyr/Code/terrier/build/debug//string_functions_test")
set_tests_properties(string_functions_test PROPERTIES  LABELS "unittest")
add_test(table_reader_test "/home/amlatyr/Code/terrier/build-support/run-test.sh" "/home/amlatyr/Code/terrier" "test" "/home/amlatyr/Code/terrier/build/debug//table_reader_test")
set_tests_properties(table_reader_test PROPERTIES  LABELS "unittest")
add_test(table_vector_iterator_test "/home/amlatyr/Code/terrier/build-support/run-test.sh" "/home/amlatyr/Code/terrier" "test" "/home/amlatyr/Code/terrier/build/debug//table_vector_iterator_test")
set_tests_properties(table_vector_iterator_test PROPERTIES  LABELS "unittest")
add_test(thread_state_container_test "/home/amlatyr/Code/terrier/build-support/run-test.sh" "/home/amlatyr/Code/terrier" "test" "/home/amlatyr/Code/terrier/build/debug//thread_state_container_test")
set_tests_properties(thread_state_container_test PROPERTIES  LABELS "unittest")
add_test(token_test "/home/amlatyr/Code/terrier/build-support/run-test.sh" "/home/amlatyr/Code/terrier" "test" "/home/amlatyr/Code/terrier/build/debug//token_test")
set_tests_properties(token_test PROPERTIES  LABELS "unittest")
add_test(type_test "/home/amlatyr/Code/terrier/build-support/run-test.sh" "/home/amlatyr/Code/terrier" "test" "/home/amlatyr/Code/terrier/build/debug//type_test")
set_tests_properties(type_test PROPERTIES  LABELS "unittest")
add_test(vector_util_test "/home/amlatyr/Code/terrier/build-support/run-test.sh" "/home/amlatyr/Code/terrier" "test" "/home/amlatyr/Code/terrier/build/debug//vector_util_test")
set_tests_properties(vector_util_test PROPERTIES  LABELS "unittest")
