# CMake generated Testfile for 
# Source directory: /Users/poojitaraj/Constraint/reb/721-P3-Constraints/test/transaction
# Build directory: /Users/poojitaraj/Constraint/reb/721-P3-Constraints/src/test/transaction
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(deferred_actions_test "/Users/poojitaraj/Constraint/reb/721-P3-Constraints/build-support/run-test.sh" "/Users/poojitaraj/Constraint/reb/721-P3-Constraints/src" "test" "/Users/poojitaraj/Constraint/reb/721-P3-Constraints/src/release//deferred_actions_test")
set_tests_properties(deferred_actions_test PROPERTIES  LABELS "unittest" _BACKTRACE_TRIPLES "/Users/poojitaraj/Constraint/reb/721-P3-Constraints/cmake_modules/BuildUtils.cmake;323;add_test;/Users/poojitaraj/Constraint/reb/721-P3-Constraints/cmake_modules/BuildUtils.cmake;333;ADD_TERRIER_TEST;/Users/poojitaraj/Constraint/reb/721-P3-Constraints/test/transaction/CMakeLists.txt;1;ADD_TERRIER_TESTS;/Users/poojitaraj/Constraint/reb/721-P3-Constraints/test/transaction/CMakeLists.txt;0;")
add_test(large_transaction_test "/Users/poojitaraj/Constraint/reb/721-P3-Constraints/build-support/run-test.sh" "/Users/poojitaraj/Constraint/reb/721-P3-Constraints/src" "test" "/Users/poojitaraj/Constraint/reb/721-P3-Constraints/src/release//large_transaction_test")
set_tests_properties(large_transaction_test PROPERTIES  LABELS "unittest" _BACKTRACE_TRIPLES "/Users/poojitaraj/Constraint/reb/721-P3-Constraints/cmake_modules/BuildUtils.cmake;323;add_test;/Users/poojitaraj/Constraint/reb/721-P3-Constraints/cmake_modules/BuildUtils.cmake;333;ADD_TERRIER_TEST;/Users/poojitaraj/Constraint/reb/721-P3-Constraints/test/transaction/CMakeLists.txt;1;ADD_TERRIER_TESTS;/Users/poojitaraj/Constraint/reb/721-P3-Constraints/test/transaction/CMakeLists.txt;0;")
add_test(mvcc_test "/Users/poojitaraj/Constraint/reb/721-P3-Constraints/build-support/run-test.sh" "/Users/poojitaraj/Constraint/reb/721-P3-Constraints/src" "test" "/Users/poojitaraj/Constraint/reb/721-P3-Constraints/src/release//mvcc_test")
set_tests_properties(mvcc_test PROPERTIES  LABELS "unittest" _BACKTRACE_TRIPLES "/Users/poojitaraj/Constraint/reb/721-P3-Constraints/cmake_modules/BuildUtils.cmake;323;add_test;/Users/poojitaraj/Constraint/reb/721-P3-Constraints/cmake_modules/BuildUtils.cmake;333;ADD_TERRIER_TEST;/Users/poojitaraj/Constraint/reb/721-P3-Constraints/test/transaction/CMakeLists.txt;1;ADD_TERRIER_TESTS;/Users/poojitaraj/Constraint/reb/721-P3-Constraints/test/transaction/CMakeLists.txt;0;")
