# CMake generated Testfile for 
# Source directory: /Users/poojitaraj/Constraint/reb/721-P3-Constraints/test/common
# Build directory: /Users/poojitaraj/Constraint/reb/721-P3-Constraints/src/test/common
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(bitmap_test "/Users/poojitaraj/Constraint/reb/721-P3-Constraints/build-support/run-test.sh" "/Users/poojitaraj/Constraint/reb/721-P3-Constraints/src" "test" "/Users/poojitaraj/Constraint/reb/721-P3-Constraints/src/release//bitmap_test")
set_tests_properties(bitmap_test PROPERTIES  LABELS "unittest" _BACKTRACE_TRIPLES "/Users/poojitaraj/Constraint/reb/721-P3-Constraints/cmake_modules/BuildUtils.cmake;323;add_test;/Users/poojitaraj/Constraint/reb/721-P3-Constraints/cmake_modules/BuildUtils.cmake;333;ADD_TERRIER_TEST;/Users/poojitaraj/Constraint/reb/721-P3-Constraints/test/common/CMakeLists.txt;1;ADD_TERRIER_TESTS;/Users/poojitaraj/Constraint/reb/721-P3-Constraints/test/common/CMakeLists.txt;0;")
add_test(concurrent_bitmap_test "/Users/poojitaraj/Constraint/reb/721-P3-Constraints/build-support/run-test.sh" "/Users/poojitaraj/Constraint/reb/721-P3-Constraints/src" "test" "/Users/poojitaraj/Constraint/reb/721-P3-Constraints/src/release//concurrent_bitmap_test")
set_tests_properties(concurrent_bitmap_test PROPERTIES  LABELS "unittest" _BACKTRACE_TRIPLES "/Users/poojitaraj/Constraint/reb/721-P3-Constraints/cmake_modules/BuildUtils.cmake;323;add_test;/Users/poojitaraj/Constraint/reb/721-P3-Constraints/cmake_modules/BuildUtils.cmake;333;ADD_TERRIER_TEST;/Users/poojitaraj/Constraint/reb/721-P3-Constraints/test/common/CMakeLists.txt;1;ADD_TERRIER_TESTS;/Users/poojitaraj/Constraint/reb/721-P3-Constraints/test/common/CMakeLists.txt;0;")
add_test(hash_util_test "/Users/poojitaraj/Constraint/reb/721-P3-Constraints/build-support/run-test.sh" "/Users/poojitaraj/Constraint/reb/721-P3-Constraints/src" "test" "/Users/poojitaraj/Constraint/reb/721-P3-Constraints/src/release//hash_util_test")
set_tests_properties(hash_util_test PROPERTIES  LABELS "unittest" _BACKTRACE_TRIPLES "/Users/poojitaraj/Constraint/reb/721-P3-Constraints/cmake_modules/BuildUtils.cmake;323;add_test;/Users/poojitaraj/Constraint/reb/721-P3-Constraints/cmake_modules/BuildUtils.cmake;333;ADD_TERRIER_TEST;/Users/poojitaraj/Constraint/reb/721-P3-Constraints/test/common/CMakeLists.txt;1;ADD_TERRIER_TESTS;/Users/poojitaraj/Constraint/reb/721-P3-Constraints/test/common/CMakeLists.txt;0;")
add_test(managed_pointer_test "/Users/poojitaraj/Constraint/reb/721-P3-Constraints/build-support/run-test.sh" "/Users/poojitaraj/Constraint/reb/721-P3-Constraints/src" "test" "/Users/poojitaraj/Constraint/reb/721-P3-Constraints/src/release//managed_pointer_test")
set_tests_properties(managed_pointer_test PROPERTIES  LABELS "unittest" _BACKTRACE_TRIPLES "/Users/poojitaraj/Constraint/reb/721-P3-Constraints/cmake_modules/BuildUtils.cmake;323;add_test;/Users/poojitaraj/Constraint/reb/721-P3-Constraints/cmake_modules/BuildUtils.cmake;333;ADD_TERRIER_TEST;/Users/poojitaraj/Constraint/reb/721-P3-Constraints/test/common/CMakeLists.txt;1;ADD_TERRIER_TESTS;/Users/poojitaraj/Constraint/reb/721-P3-Constraints/test/common/CMakeLists.txt;0;")
add_test(object_pool_test "/Users/poojitaraj/Constraint/reb/721-P3-Constraints/build-support/run-test.sh" "/Users/poojitaraj/Constraint/reb/721-P3-Constraints/src" "test" "/Users/poojitaraj/Constraint/reb/721-P3-Constraints/src/release//object_pool_test")
set_tests_properties(object_pool_test PROPERTIES  LABELS "unittest" _BACKTRACE_TRIPLES "/Users/poojitaraj/Constraint/reb/721-P3-Constraints/cmake_modules/BuildUtils.cmake;323;add_test;/Users/poojitaraj/Constraint/reb/721-P3-Constraints/cmake_modules/BuildUtils.cmake;333;ADD_TERRIER_TEST;/Users/poojitaraj/Constraint/reb/721-P3-Constraints/test/common/CMakeLists.txt;1;ADD_TERRIER_TESTS;/Users/poojitaraj/Constraint/reb/721-P3-Constraints/test/common/CMakeLists.txt;0;")
add_test(perf_monitor_test "/Users/poojitaraj/Constraint/reb/721-P3-Constraints/build-support/run-test.sh" "/Users/poojitaraj/Constraint/reb/721-P3-Constraints/src" "test" "/Users/poojitaraj/Constraint/reb/721-P3-Constraints/src/release//perf_monitor_test")
set_tests_properties(perf_monitor_test PROPERTIES  LABELS "unittest" _BACKTRACE_TRIPLES "/Users/poojitaraj/Constraint/reb/721-P3-Constraints/cmake_modules/BuildUtils.cmake;323;add_test;/Users/poojitaraj/Constraint/reb/721-P3-Constraints/cmake_modules/BuildUtils.cmake;333;ADD_TERRIER_TEST;/Users/poojitaraj/Constraint/reb/721-P3-Constraints/test/common/CMakeLists.txt;1;ADD_TERRIER_TESTS;/Users/poojitaraj/Constraint/reb/721-P3-Constraints/test/common/CMakeLists.txt;0;")
add_test(performance_counter_test "/Users/poojitaraj/Constraint/reb/721-P3-Constraints/build-support/run-test.sh" "/Users/poojitaraj/Constraint/reb/721-P3-Constraints/src" "test" "/Users/poojitaraj/Constraint/reb/721-P3-Constraints/src/release//performance_counter_test")
set_tests_properties(performance_counter_test PROPERTIES  LABELS "unittest" _BACKTRACE_TRIPLES "/Users/poojitaraj/Constraint/reb/721-P3-Constraints/cmake_modules/BuildUtils.cmake;323;add_test;/Users/poojitaraj/Constraint/reb/721-P3-Constraints/cmake_modules/BuildUtils.cmake;333;ADD_TERRIER_TEST;/Users/poojitaraj/Constraint/reb/721-P3-Constraints/test/common/CMakeLists.txt;1;ADD_TERRIER_TESTS;/Users/poojitaraj/Constraint/reb/721-P3-Constraints/test/common/CMakeLists.txt;0;")
add_test(rusage_monitor_test "/Users/poojitaraj/Constraint/reb/721-P3-Constraints/build-support/run-test.sh" "/Users/poojitaraj/Constraint/reb/721-P3-Constraints/src" "test" "/Users/poojitaraj/Constraint/reb/721-P3-Constraints/src/release//rusage_monitor_test")
set_tests_properties(rusage_monitor_test PROPERTIES  LABELS "unittest" _BACKTRACE_TRIPLES "/Users/poojitaraj/Constraint/reb/721-P3-Constraints/cmake_modules/BuildUtils.cmake;323;add_test;/Users/poojitaraj/Constraint/reb/721-P3-Constraints/cmake_modules/BuildUtils.cmake;333;ADD_TERRIER_TEST;/Users/poojitaraj/Constraint/reb/721-P3-Constraints/test/common/CMakeLists.txt;1;ADD_TERRIER_TESTS;/Users/poojitaraj/Constraint/reb/721-P3-Constraints/test/common/CMakeLists.txt;0;")
add_test(stat_registry_test "/Users/poojitaraj/Constraint/reb/721-P3-Constraints/build-support/run-test.sh" "/Users/poojitaraj/Constraint/reb/721-P3-Constraints/src" "test" "/Users/poojitaraj/Constraint/reb/721-P3-Constraints/src/release//stat_registry_test")
set_tests_properties(stat_registry_test PROPERTIES  LABELS "unittest" _BACKTRACE_TRIPLES "/Users/poojitaraj/Constraint/reb/721-P3-Constraints/cmake_modules/BuildUtils.cmake;323;add_test;/Users/poojitaraj/Constraint/reb/721-P3-Constraints/cmake_modules/BuildUtils.cmake;333;ADD_TERRIER_TEST;/Users/poojitaraj/Constraint/reb/721-P3-Constraints/test/common/CMakeLists.txt;1;ADD_TERRIER_TESTS;/Users/poojitaraj/Constraint/reb/721-P3-Constraints/test/common/CMakeLists.txt;0;")
add_test(worker_pool_test "/Users/poojitaraj/Constraint/reb/721-P3-Constraints/build-support/run-test.sh" "/Users/poojitaraj/Constraint/reb/721-P3-Constraints/src" "test" "/Users/poojitaraj/Constraint/reb/721-P3-Constraints/src/release//worker_pool_test")
set_tests_properties(worker_pool_test PROPERTIES  LABELS "unittest" _BACKTRACE_TRIPLES "/Users/poojitaraj/Constraint/reb/721-P3-Constraints/cmake_modules/BuildUtils.cmake;323;add_test;/Users/poojitaraj/Constraint/reb/721-P3-Constraints/cmake_modules/BuildUtils.cmake;333;ADD_TERRIER_TEST;/Users/poojitaraj/Constraint/reb/721-P3-Constraints/test/common/CMakeLists.txt;1;ADD_TERRIER_TESTS;/Users/poojitaraj/Constraint/reb/721-P3-Constraints/test/common/CMakeLists.txt;0;")
