# CMake generated Testfile for 
# Source directory: /Users/vivianhuang/desktop/terrier/test/storage
# Build directory: /Users/vivianhuang/desktop/terrier/release/test/storage
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(bwtree_index_test "/Users/vivianhuang/desktop/terrier/build-support/run-test.sh" "/Users/vivianhuang/desktop/terrier/release" "test" "/Users/vivianhuang/desktop/terrier/release/release//bwtree_index_test")
set_tests_properties(bwtree_index_test PROPERTIES  LABELS "unittest" _BACKTRACE_TRIPLES "/Users/vivianhuang/desktop/terrier/cmake_modules/BuildUtils.cmake;317;add_test;/Users/vivianhuang/desktop/terrier/cmake_modules/BuildUtils.cmake;327;ADD_TERRIER_TEST;/Users/vivianhuang/desktop/terrier/test/storage/CMakeLists.txt;1;ADD_TERRIER_TESTS;/Users/vivianhuang/desktop/terrier/test/storage/CMakeLists.txt;0;")
add_test(bwtree_key_test "/Users/vivianhuang/desktop/terrier/build-support/run-test.sh" "/Users/vivianhuang/desktop/terrier/release" "test" "/Users/vivianhuang/desktop/terrier/release/release//bwtree_key_test")
set_tests_properties(bwtree_key_test PROPERTIES  LABELS "unittest" _BACKTRACE_TRIPLES "/Users/vivianhuang/desktop/terrier/cmake_modules/BuildUtils.cmake;317;add_test;/Users/vivianhuang/desktop/terrier/cmake_modules/BuildUtils.cmake;327;ADD_TERRIER_TEST;/Users/vivianhuang/desktop/terrier/test/storage/CMakeLists.txt;1;ADD_TERRIER_TESTS;/Users/vivianhuang/desktop/terrier/test/storage/CMakeLists.txt;0;")
add_test(bwtree_test "/Users/vivianhuang/desktop/terrier/build-support/run-test.sh" "/Users/vivianhuang/desktop/terrier/release" "test" "/Users/vivianhuang/desktop/terrier/release/release//bwtree_test")
set_tests_properties(bwtree_test PROPERTIES  LABELS "unittest" _BACKTRACE_TRIPLES "/Users/vivianhuang/desktop/terrier/cmake_modules/BuildUtils.cmake;317;add_test;/Users/vivianhuang/desktop/terrier/cmake_modules/BuildUtils.cmake;327;ADD_TERRIER_TEST;/Users/vivianhuang/desktop/terrier/test/storage/CMakeLists.txt;1;ADD_TERRIER_TESTS;/Users/vivianhuang/desktop/terrier/test/storage/CMakeLists.txt;0;")
add_test(data_table_concurrent_test "/Users/vivianhuang/desktop/terrier/build-support/run-test.sh" "/Users/vivianhuang/desktop/terrier/release" "test" "/Users/vivianhuang/desktop/terrier/release/release//data_table_concurrent_test")
set_tests_properties(data_table_concurrent_test PROPERTIES  LABELS "unittest" _BACKTRACE_TRIPLES "/Users/vivianhuang/desktop/terrier/cmake_modules/BuildUtils.cmake;317;add_test;/Users/vivianhuang/desktop/terrier/cmake_modules/BuildUtils.cmake;327;ADD_TERRIER_TEST;/Users/vivianhuang/desktop/terrier/test/storage/CMakeLists.txt;1;ADD_TERRIER_TESTS;/Users/vivianhuang/desktop/terrier/test/storage/CMakeLists.txt;0;")
add_test(data_table_test "/Users/vivianhuang/desktop/terrier/build-support/run-test.sh" "/Users/vivianhuang/desktop/terrier/release" "test" "/Users/vivianhuang/desktop/terrier/release/release//data_table_test")
set_tests_properties(data_table_test PROPERTIES  LABELS "unittest" _BACKTRACE_TRIPLES "/Users/vivianhuang/desktop/terrier/cmake_modules/BuildUtils.cmake;317;add_test;/Users/vivianhuang/desktop/terrier/cmake_modules/BuildUtils.cmake;327;ADD_TERRIER_TEST;/Users/vivianhuang/desktop/terrier/test/storage/CMakeLists.txt;1;ADD_TERRIER_TESTS;/Users/vivianhuang/desktop/terrier/test/storage/CMakeLists.txt;0;")
add_test(delta_record_test "/Users/vivianhuang/desktop/terrier/build-support/run-test.sh" "/Users/vivianhuang/desktop/terrier/release" "test" "/Users/vivianhuang/desktop/terrier/release/release//delta_record_test")
set_tests_properties(delta_record_test PROPERTIES  LABELS "unittest" _BACKTRACE_TRIPLES "/Users/vivianhuang/desktop/terrier/cmake_modules/BuildUtils.cmake;317;add_test;/Users/vivianhuang/desktop/terrier/cmake_modules/BuildUtils.cmake;327;ADD_TERRIER_TEST;/Users/vivianhuang/desktop/terrier/test/storage/CMakeLists.txt;1;ADD_TERRIER_TESTS;/Users/vivianhuang/desktop/terrier/test/storage/CMakeLists.txt;0;")
add_test(garbage_collector_test "/Users/vivianhuang/desktop/terrier/build-support/run-test.sh" "/Users/vivianhuang/desktop/terrier/release" "test" "/Users/vivianhuang/desktop/terrier/release/release//garbage_collector_test")
set_tests_properties(garbage_collector_test PROPERTIES  LABELS "unittest" _BACKTRACE_TRIPLES "/Users/vivianhuang/desktop/terrier/cmake_modules/BuildUtils.cmake;317;add_test;/Users/vivianhuang/desktop/terrier/cmake_modules/BuildUtils.cmake;327;ADD_TERRIER_TEST;/Users/vivianhuang/desktop/terrier/test/storage/CMakeLists.txt;1;ADD_TERRIER_TESTS;/Users/vivianhuang/desktop/terrier/test/storage/CMakeLists.txt;0;")
add_test(large_garbage_collector_test "/Users/vivianhuang/desktop/terrier/build-support/run-test.sh" "/Users/vivianhuang/desktop/terrier/release" "test" "/Users/vivianhuang/desktop/terrier/release/release//large_garbage_collector_test")
set_tests_properties(large_garbage_collector_test PROPERTIES  LABELS "unittest" _BACKTRACE_TRIPLES "/Users/vivianhuang/desktop/terrier/cmake_modules/BuildUtils.cmake;317;add_test;/Users/vivianhuang/desktop/terrier/cmake_modules/BuildUtils.cmake;327;ADD_TERRIER_TEST;/Users/vivianhuang/desktop/terrier/test/storage/CMakeLists.txt;1;ADD_TERRIER_TESTS;/Users/vivianhuang/desktop/terrier/test/storage/CMakeLists.txt;0;")
add_test(log_test "/Users/vivianhuang/desktop/terrier/build-support/run-test.sh" "/Users/vivianhuang/desktop/terrier/release" "test" "/Users/vivianhuang/desktop/terrier/release/release//log_test")
set_tests_properties(log_test PROPERTIES  LABELS "unittest" _BACKTRACE_TRIPLES "/Users/vivianhuang/desktop/terrier/cmake_modules/BuildUtils.cmake;317;add_test;/Users/vivianhuang/desktop/terrier/cmake_modules/BuildUtils.cmake;327;ADD_TERRIER_TEST;/Users/vivianhuang/desktop/terrier/test/storage/CMakeLists.txt;1;ADD_TERRIER_TESTS;/Users/vivianhuang/desktop/terrier/test/storage/CMakeLists.txt;0;")
add_test(projected_row_test "/Users/vivianhuang/desktop/terrier/build-support/run-test.sh" "/Users/vivianhuang/desktop/terrier/release" "test" "/Users/vivianhuang/desktop/terrier/release/release//projected_row_test")
set_tests_properties(projected_row_test PROPERTIES  LABELS "unittest" _BACKTRACE_TRIPLES "/Users/vivianhuang/desktop/terrier/cmake_modules/BuildUtils.cmake;317;add_test;/Users/vivianhuang/desktop/terrier/cmake_modules/BuildUtils.cmake;327;ADD_TERRIER_TEST;/Users/vivianhuang/desktop/terrier/test/storage/CMakeLists.txt;1;ADD_TERRIER_TESTS;/Users/vivianhuang/desktop/terrier/test/storage/CMakeLists.txt;0;")
add_test(storage_util_test "/Users/vivianhuang/desktop/terrier/build-support/run-test.sh" "/Users/vivianhuang/desktop/terrier/release" "test" "/Users/vivianhuang/desktop/terrier/release/release//storage_util_test")
set_tests_properties(storage_util_test PROPERTIES  LABELS "unittest" _BACKTRACE_TRIPLES "/Users/vivianhuang/desktop/terrier/cmake_modules/BuildUtils.cmake;317;add_test;/Users/vivianhuang/desktop/terrier/cmake_modules/BuildUtils.cmake;327;ADD_TERRIER_TEST;/Users/vivianhuang/desktop/terrier/test/storage/CMakeLists.txt;1;ADD_TERRIER_TESTS;/Users/vivianhuang/desktop/terrier/test/storage/CMakeLists.txt;0;")
add_test(tuple_access_strategy_test "/Users/vivianhuang/desktop/terrier/build-support/run-test.sh" "/Users/vivianhuang/desktop/terrier/release" "test" "/Users/vivianhuang/desktop/terrier/release/release//tuple_access_strategy_test")
set_tests_properties(tuple_access_strategy_test PROPERTIES  LABELS "unittest" _BACKTRACE_TRIPLES "/Users/vivianhuang/desktop/terrier/cmake_modules/BuildUtils.cmake;317;add_test;/Users/vivianhuang/desktop/terrier/cmake_modules/BuildUtils.cmake;327;ADD_TERRIER_TEST;/Users/vivianhuang/desktop/terrier/test/storage/CMakeLists.txt;1;ADD_TERRIER_TESTS;/Users/vivianhuang/desktop/terrier/test/storage/CMakeLists.txt;0;")
add_test(varlen_entry_test "/Users/vivianhuang/desktop/terrier/build-support/run-test.sh" "/Users/vivianhuang/desktop/terrier/release" "test" "/Users/vivianhuang/desktop/terrier/release/release//varlen_entry_test")
set_tests_properties(varlen_entry_test PROPERTIES  LABELS "unittest" _BACKTRACE_TRIPLES "/Users/vivianhuang/desktop/terrier/cmake_modules/BuildUtils.cmake;317;add_test;/Users/vivianhuang/desktop/terrier/cmake_modules/BuildUtils.cmake;327;ADD_TERRIER_TEST;/Users/vivianhuang/desktop/terrier/test/storage/CMakeLists.txt;1;ADD_TERRIER_TESTS;/Users/vivianhuang/desktop/terrier/test/storage/CMakeLists.txt;0;")
