# CMake generated Testfile for 
# Source directory: /Users/vivianhuang/desktop/terrier/test/common
# Build directory: /Users/vivianhuang/desktop/terrier/release/test/common
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(bitmap_test "/Users/vivianhuang/desktop/terrier/build-support/run-test.sh" "/Users/vivianhuang/desktop/terrier/release" "test" "/Users/vivianhuang/desktop/terrier/release/release//bitmap_test")
set_tests_properties(bitmap_test PROPERTIES  LABELS "unittest" _BACKTRACE_TRIPLES "/Users/vivianhuang/desktop/terrier/cmake_modules/BuildUtils.cmake;317;add_test;/Users/vivianhuang/desktop/terrier/cmake_modules/BuildUtils.cmake;327;ADD_TERRIER_TEST;/Users/vivianhuang/desktop/terrier/test/common/CMakeLists.txt;1;ADD_TERRIER_TESTS;/Users/vivianhuang/desktop/terrier/test/common/CMakeLists.txt;0;")
add_test(concurrent_bitmap_test "/Users/vivianhuang/desktop/terrier/build-support/run-test.sh" "/Users/vivianhuang/desktop/terrier/release" "test" "/Users/vivianhuang/desktop/terrier/release/release//concurrent_bitmap_test")
set_tests_properties(concurrent_bitmap_test PROPERTIES  LABELS "unittest" _BACKTRACE_TRIPLES "/Users/vivianhuang/desktop/terrier/cmake_modules/BuildUtils.cmake;317;add_test;/Users/vivianhuang/desktop/terrier/cmake_modules/BuildUtils.cmake;327;ADD_TERRIER_TEST;/Users/vivianhuang/desktop/terrier/test/common/CMakeLists.txt;1;ADD_TERRIER_TESTS;/Users/vivianhuang/desktop/terrier/test/common/CMakeLists.txt;0;")
add_test(managed_pointer_test "/Users/vivianhuang/desktop/terrier/build-support/run-test.sh" "/Users/vivianhuang/desktop/terrier/release" "test" "/Users/vivianhuang/desktop/terrier/release/release//managed_pointer_test")
set_tests_properties(managed_pointer_test PROPERTIES  LABELS "unittest" _BACKTRACE_TRIPLES "/Users/vivianhuang/desktop/terrier/cmake_modules/BuildUtils.cmake;317;add_test;/Users/vivianhuang/desktop/terrier/cmake_modules/BuildUtils.cmake;327;ADD_TERRIER_TEST;/Users/vivianhuang/desktop/terrier/test/common/CMakeLists.txt;1;ADD_TERRIER_TESTS;/Users/vivianhuang/desktop/terrier/test/common/CMakeLists.txt;0;")
add_test(object_pool_test "/Users/vivianhuang/desktop/terrier/build-support/run-test.sh" "/Users/vivianhuang/desktop/terrier/release" "test" "/Users/vivianhuang/desktop/terrier/release/release//object_pool_test")
set_tests_properties(object_pool_test PROPERTIES  LABELS "unittest" _BACKTRACE_TRIPLES "/Users/vivianhuang/desktop/terrier/cmake_modules/BuildUtils.cmake;317;add_test;/Users/vivianhuang/desktop/terrier/cmake_modules/BuildUtils.cmake;327;ADD_TERRIER_TEST;/Users/vivianhuang/desktop/terrier/test/common/CMakeLists.txt;1;ADD_TERRIER_TESTS;/Users/vivianhuang/desktop/terrier/test/common/CMakeLists.txt;0;")
add_test(performance_counter_test "/Users/vivianhuang/desktop/terrier/build-support/run-test.sh" "/Users/vivianhuang/desktop/terrier/release" "test" "/Users/vivianhuang/desktop/terrier/release/release//performance_counter_test")
set_tests_properties(performance_counter_test PROPERTIES  LABELS "unittest" _BACKTRACE_TRIPLES "/Users/vivianhuang/desktop/terrier/cmake_modules/BuildUtils.cmake;317;add_test;/Users/vivianhuang/desktop/terrier/cmake_modules/BuildUtils.cmake;327;ADD_TERRIER_TEST;/Users/vivianhuang/desktop/terrier/test/common/CMakeLists.txt;1;ADD_TERRIER_TESTS;/Users/vivianhuang/desktop/terrier/test/common/CMakeLists.txt;0;")
add_test(stat_registry_test "/Users/vivianhuang/desktop/terrier/build-support/run-test.sh" "/Users/vivianhuang/desktop/terrier/release" "test" "/Users/vivianhuang/desktop/terrier/release/release//stat_registry_test")
set_tests_properties(stat_registry_test PROPERTIES  LABELS "unittest" _BACKTRACE_TRIPLES "/Users/vivianhuang/desktop/terrier/cmake_modules/BuildUtils.cmake;317;add_test;/Users/vivianhuang/desktop/terrier/cmake_modules/BuildUtils.cmake;327;ADD_TERRIER_TEST;/Users/vivianhuang/desktop/terrier/test/common/CMakeLists.txt;1;ADD_TERRIER_TESTS;/Users/vivianhuang/desktop/terrier/test/common/CMakeLists.txt;0;")
add_test(worker_pool_test "/Users/vivianhuang/desktop/terrier/build-support/run-test.sh" "/Users/vivianhuang/desktop/terrier/release" "test" "/Users/vivianhuang/desktop/terrier/release/release//worker_pool_test")
set_tests_properties(worker_pool_test PROPERTIES  LABELS "unittest" _BACKTRACE_TRIPLES "/Users/vivianhuang/desktop/terrier/cmake_modules/BuildUtils.cmake;317;add_test;/Users/vivianhuang/desktop/terrier/cmake_modules/BuildUtils.cmake;327;ADD_TERRIER_TEST;/Users/vivianhuang/desktop/terrier/test/common/CMakeLists.txt;1;ADD_TERRIER_TESTS;/Users/vivianhuang/desktop/terrier/test/common/CMakeLists.txt;0;")
