# CMake generated Testfile for 
# Source directory: /Users/poojitaraj/Constraint/reb/721-P3-Constraints/test/parser
# Build directory: /Users/poojitaraj/Constraint/reb/721-P3-Constraints/src/test/parser
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(constant_value_expression_test "/Users/poojitaraj/Constraint/reb/721-P3-Constraints/build-support/run-test.sh" "/Users/poojitaraj/Constraint/reb/721-P3-Constraints/src" "test" "/Users/poojitaraj/Constraint/reb/721-P3-Constraints/src/release//constant_value_expression_test")
set_tests_properties(constant_value_expression_test PROPERTIES  LABELS "unittest" _BACKTRACE_TRIPLES "/Users/poojitaraj/Constraint/reb/721-P3-Constraints/cmake_modules/BuildUtils.cmake;323;add_test;/Users/poojitaraj/Constraint/reb/721-P3-Constraints/cmake_modules/BuildUtils.cmake;333;ADD_TERRIER_TEST;/Users/poojitaraj/Constraint/reb/721-P3-Constraints/test/parser/CMakeLists.txt;1;ADD_TERRIER_TESTS;/Users/poojitaraj/Constraint/reb/721-P3-Constraints/test/parser/CMakeLists.txt;0;")
add_test(expression_defs_test "/Users/poojitaraj/Constraint/reb/721-P3-Constraints/build-support/run-test.sh" "/Users/poojitaraj/Constraint/reb/721-P3-Constraints/src" "test" "/Users/poojitaraj/Constraint/reb/721-P3-Constraints/src/release//expression_defs_test")
set_tests_properties(expression_defs_test PROPERTIES  LABELS "unittest" _BACKTRACE_TRIPLES "/Users/poojitaraj/Constraint/reb/721-P3-Constraints/cmake_modules/BuildUtils.cmake;323;add_test;/Users/poojitaraj/Constraint/reb/721-P3-Constraints/cmake_modules/BuildUtils.cmake;333;ADD_TERRIER_TEST;/Users/poojitaraj/Constraint/reb/721-P3-Constraints/test/parser/CMakeLists.txt;1;ADD_TERRIER_TESTS;/Users/poojitaraj/Constraint/reb/721-P3-Constraints/test/parser/CMakeLists.txt;0;")
add_test(expression_test "/Users/poojitaraj/Constraint/reb/721-P3-Constraints/build-support/run-test.sh" "/Users/poojitaraj/Constraint/reb/721-P3-Constraints/src" "test" "/Users/poojitaraj/Constraint/reb/721-P3-Constraints/src/release//expression_test")
set_tests_properties(expression_test PROPERTIES  LABELS "unittest" _BACKTRACE_TRIPLES "/Users/poojitaraj/Constraint/reb/721-P3-Constraints/cmake_modules/BuildUtils.cmake;323;add_test;/Users/poojitaraj/Constraint/reb/721-P3-Constraints/cmake_modules/BuildUtils.cmake;333;ADD_TERRIER_TEST;/Users/poojitaraj/Constraint/reb/721-P3-Constraints/test/parser/CMakeLists.txt;1;ADD_TERRIER_TESTS;/Users/poojitaraj/Constraint/reb/721-P3-Constraints/test/parser/CMakeLists.txt;0;")
add_test(expression_util_test "/Users/poojitaraj/Constraint/reb/721-P3-Constraints/build-support/run-test.sh" "/Users/poojitaraj/Constraint/reb/721-P3-Constraints/src" "test" "/Users/poojitaraj/Constraint/reb/721-P3-Constraints/src/release//expression_util_test")
set_tests_properties(expression_util_test PROPERTIES  LABELS "unittest" _BACKTRACE_TRIPLES "/Users/poojitaraj/Constraint/reb/721-P3-Constraints/cmake_modules/BuildUtils.cmake;323;add_test;/Users/poojitaraj/Constraint/reb/721-P3-Constraints/cmake_modules/BuildUtils.cmake;333;ADD_TERRIER_TEST;/Users/poojitaraj/Constraint/reb/721-P3-Constraints/test/parser/CMakeLists.txt;1;ADD_TERRIER_TESTS;/Users/poojitaraj/Constraint/reb/721-P3-Constraints/test/parser/CMakeLists.txt;0;")
add_test(parser_test "/Users/poojitaraj/Constraint/reb/721-P3-Constraints/build-support/run-test.sh" "/Users/poojitaraj/Constraint/reb/721-P3-Constraints/src" "test" "/Users/poojitaraj/Constraint/reb/721-P3-Constraints/src/release//parser_test")
set_tests_properties(parser_test PROPERTIES  LABELS "unittest" _BACKTRACE_TRIPLES "/Users/poojitaraj/Constraint/reb/721-P3-Constraints/cmake_modules/BuildUtils.cmake;323;add_test;/Users/poojitaraj/Constraint/reb/721-P3-Constraints/cmake_modules/BuildUtils.cmake;333;ADD_TERRIER_TEST;/Users/poojitaraj/Constraint/reb/721-P3-Constraints/test/parser/CMakeLists.txt;1;ADD_TERRIER_TESTS;/Users/poojitaraj/Constraint/reb/721-P3-Constraints/test/parser/CMakeLists.txt;0;")
add_test(pg_parser_test "/Users/poojitaraj/Constraint/reb/721-P3-Constraints/build-support/run-test.sh" "/Users/poojitaraj/Constraint/reb/721-P3-Constraints/src" "test" "/Users/poojitaraj/Constraint/reb/721-P3-Constraints/src/release//pg_parser_test")
set_tests_properties(pg_parser_test PROPERTIES  LABELS "unittest" _BACKTRACE_TRIPLES "/Users/poojitaraj/Constraint/reb/721-P3-Constraints/cmake_modules/BuildUtils.cmake;323;add_test;/Users/poojitaraj/Constraint/reb/721-P3-Constraints/cmake_modules/BuildUtils.cmake;333;ADD_TERRIER_TEST;/Users/poojitaraj/Constraint/reb/721-P3-Constraints/test/parser/CMakeLists.txt;1;ADD_TERRIER_TESTS;/Users/poojitaraj/Constraint/reb/721-P3-Constraints/test/parser/CMakeLists.txt;0;")
