set(command "/usr/local/Cellar/cmake/3.14.5/bin/cmake;-P;/Users/vivianhuang/desktop/terrier/release/gflags_ep-prefix/src/gflags_ep-stamp/download-gflags_ep.cmake")

execute_process(COMMAND ${command} RESULT_VARIABLE result)
if(result)
  set(msg "Command failed (${result}):\n")
  foreach(arg IN LISTS command)
    set(msg "${msg} '${arg}'")
  endforeach()
  message(FATAL_ERROR "${msg}")
endif()
set(command "/usr/local/Cellar/cmake/3.14.5/bin/cmake;-P;/Users/vivianhuang/desktop/terrier/release/gflags_ep-prefix/src/gflags_ep-stamp/verify-gflags_ep.cmake")

execute_process(COMMAND ${command} RESULT_VARIABLE result)
if(result)
  set(msg "Command failed (${result}):\n")
  foreach(arg IN LISTS command)
    set(msg "${msg} '${arg}'")
  endforeach()
  message(FATAL_ERROR "${msg}")
endif()
set(command "/usr/local/Cellar/cmake/3.14.5/bin/cmake;-P;/Users/vivianhuang/desktop/terrier/release/gflags_ep-prefix/src/gflags_ep-stamp/extract-gflags_ep.cmake")

execute_process(COMMAND ${command} RESULT_VARIABLE result)
if(result)
  set(msg "Command failed (${result}):\n")
  foreach(arg IN LISTS command)
    set(msg "${msg} '${arg}'")
  endforeach()
  message(FATAL_ERROR "${msg}")
endif()
