if(USE_SANITIZER)
  if (USE_SANITIZER STREQUAL "Address")
    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -fsanitize=address")
    message(STATUS "AddressSanitizer enabled.")
  elseif (USE_SANITIZER STREQUAL "Undefined")
    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -fsanitize=undefined -fno-sanitize=vptr,function -fno-sanitize-recover=all")
    message(STATUS "UndefinedBehaviorSanitizer enabled.")
  elseif (USE_SANITIZER STREQUAL "Thread")
    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -fsanitize=thread")
  elseif (USE_SANITIZER STREQUAL "Address;Undefined" OR
          USE_SANITIZER STREQUAL "Undefined;Address")
    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -fsanitize=address,undefined -fno-sanitize=vptr,function -fno-sanitize-recover=all")
    message(STATUS "AddressSanitizer and UndefinedBehaviorSanitizer enabled.")
  else()
    message(FATAL_ERROR "Unsupported value of USE_SANITIZER: ${USE_SANITIZER}")
  endif()
endif()